# ============================================================
# Cloud Build Pipeline
# 1. Run unit tests
# 2. Auto-version + upload model artifacts to GCS (public)
# 3. Build Docker image
# 4. Push to Artifact Registry
# 5. Deploy to Cloud Run with correct MODEL_PATH + PREPROCESSOR_PATH
# ============================================================

substitutions:
  _PROJECT_ID: "josiahs-project-475720"
  _REGION: "us-east1"
  _REPOSITORY: "carprice-repo"
  _SERVICE_NAME: "carprice-api"
  _BUCKET_NAME: "carprice-artifacts"

steps:
  # 1️⃣ Run unit tests
  - name: "python:3.11"
    id: "run-tests"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "=== Running unit tests ==="
        pip install -r requirements.txt
        pytest -q || (echo "❌ Unit tests failed" && exit 1)
        echo "✅ Tests completed successfully."

  # 2️⃣ Auto-version + upload artifacts to GCS
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "upload-versioned-artifacts"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "=== Generating version tag ==="
        VERSION=$(date +"%Y%m%d-%H%M")-${SHORT_SHA}
        echo "VERSION=${VERSION}" > version.txt
        echo "Generated version: ${VERSION}"

        echo "=== Uploading versioned artifacts ==="
        gsutil cp artifacts/model.json gs://${_BUCKET_NAME}/models/model-${VERSION}.json
        gsutil cp artifacts/preprocessor.pkl gs://${_BUCKET_NAME}/models/preprocessor-${VERSION}.pkl

        echo "=== Making files public (no service accounts needed) ==="
        gsutil acl ch -u AllUsers:R gs://${_BUCKET_NAME}/models/model-${VERSION}.json
        gsutil acl ch -u AllUsers:R gs://${_BUCKET_NAME}/models/preprocessor-${VERSION}.pkl

        echo "MODEL_PUBLIC_URL=https://storage.googleapis.com/${_BUCKET_NAME}/models/model-${VERSION}.json" > model_url.txt
        echo "PREPROCESSOR_PUBLIC_URL=https://storage.googleapis.com/${_BUCKET_NAME}/models/preprocessor-${VERSION}.pkl" > prep_url.txt

        echo "Uploaded:"
        cat model_url.txt
        cat prep_url.txt

  # 3️⃣ Build the image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
        "."
      ]

  # 4️⃣ Push the image
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
      ]

  # 5️⃣ Deploy to Cloud Run with NEW versioned model paths
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-cloud-run"
    entrypoint: bash
    args:
      - "-c"
      - |
        MODEL_URL=$(cat model_url.txt | cut -d '=' -f2)
        PREP_URL=$(cat prep_url.txt | cut -d '=' -f2)

        echo "Deploying with:"
        echo "MODEL_PATH=${MODEL_URL}"
        echo "PREPROCESSOR_PATH=${PREP_URL}"

        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --concurrency 1 \
          --timeout 600s \
          --set-env-vars OMP_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,XGBOOST_NUM_THREADS=1 \
          --set-env-vars GUNICORN_WORKERS=1,GUNICORN_THREADS=1 \
          --set-env-vars MODEL_PATH=${MODEL_URL},PREPROCESSOR_PATH=${PREP_URL}

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
