
# Steps:
# 1️⃣ Run unit tests
# 2️⃣ Upload model artifacts to GCS
# 3️⃣ Build container image
# 4️⃣ Push to Artifact Registry
# 5️⃣ Deploy to Cloud Run
# ============================================================

substitutions:
  _PROJECT_ID: "josiahs-project-475720"
  _REGION: "us-east1"
  _REPOSITORY: "carprice-repo-east"       
  _SERVICE_NAME: "carprice-api"      
  _BUCKET_NAME: "carprice-artifacts" 

steps:
  - name: "python:3.11"
    id: "run-tests"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "=== Running unit tests ==="
        pip install -r requirements.txt
        pytest -q || (echo "❌ Unit tests failed" && exit 1)
        echo "✅ Tests completed successfully."

  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "upload-artifacts"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "=== Uploading model artifacts to GCS ==="
        gsutil cp /workspace/artifacts/model.json gs://${_BUCKET_NAME}/models/model.json
        gsutil cp /workspace/artifacts/preprocessor.pkl gs://${_BUCKET_NAME}/models/preprocessor.pkl
        echo "✅ Model and preprocessor uploaded to GCS."

  
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
        "."
      ]

  
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-cloud-run"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "2Gi",
        "--cpu",
        "2",
        "--concurrency",
        "80",
        "--timeout",
        "1800s",
        "--set-env-vars",
        "MODEL_PATH=gs://${_BUCKET_NAME}/models/model.json,PREPROCESSOR_PATH=gs://${_BUCKET_NAME}/models/preprocessor.pkl,LOG_LEVEL=info,GUNICORN_THREADS=2",
        "--set-env-vars",
        "GUNICORN_WORKERS=3"
      ]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY